# Generated by Django 4.2.2 on 2023-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_talaba_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='universitet',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
